sudo: required
services:
  - docker

before_install:
  - docker build -t azaa1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run azaa1/react-test npm test -- --coverage

after_success:
  - docker build -t azaa1/multi-client ./client
  - docker build -t azaa1/multi-nginx ./nginx
  - docker build -t azaa1/multi-server ./server
  - docker build -t azaa1/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push azaa1/multi-client
  - docker push azaa1/multi-nginx
  - docker push azaa1/multi-server
  - docker push azaa1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env:  MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-505502081114
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: 
    secure: $AWS_SECRET_KEY
